name: time
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  get: ^4.6.6
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.6
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  device_preview: ^1.2.0
  google_fonts: ^6.2.1
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  mime: ^1.0.5
  flutter_spinkit: ^5.2.1
  curved_navigation_bar: ^1.0.6
  file_picker: ^8.1.7
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
